# Change these first
owner: bronya5th # Your GitHub username
repo: upptime # Your Github repository name
user-agent: bronya5th
# Add your sites here
sites:
# - name: Secret Site
#   url: $SECRET_SITE
  - name: Gitea
    url: $GITEA
  - name: Halo-blog
    url: $HALO_BLOG
  - name: Misskey
    url: $MISSKEY
  - name: Umami
    url: $UMAMI_URL
  - name: n8n
    url: $N8N_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/bronya5th/some-others/main/favicon.ico
  # https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bronya5th-Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  
  navbar:
  #  - title: Status
  #    href: /
    - title: This-repository-in-gh
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
